import type { Product } from '~~/shared/types/product'

// Limited drop date ~30 days from now
const limitedDropDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString()

export const products: Product[] = [
  // ── Navigation Gear ──────────────────────────────────────────
  {
    sku: 'NAV-ARC-001',
    slug: 'arc-navigator-pro',
    name: 'Arc Navigator Pro',
    tagline: 'AI-guided wayfinding for the uncharted',
    description: 'The Arc Navigator Pro combines multi-constellation GNSS with predictive AI terrain mapping. Rated to -40C with a sunlight-readable AMOLED display, it learns your pace and suggests optimal routes in real time.',
    price: 549,
    compareAtPrice: 649,
    category: 'navigation-gear',
    activities: ['hiking', 'climbing', 'trail-running'],
    techLevel: 'ai-powered',
    techSpecs: [
      { label: 'Display', value: '3.2"', unit: 'AMOLED' },
      { label: 'Battery', value: '72', unit: 'hrs' },
      { label: 'GNSS', value: 'Multi-constellation', unit: 'L1/L5' },
      { label: 'Weight', value: '142', unit: 'g' },
      { label: 'Water Rating', value: 'IPX8', unit: '10m' },
      { label: 'Operating Temp', value: '-40 to 60', unit: 'C' },
    ],
    featured: true,
    limitedDrop: false,
    accentColor: 'teal',
    storyExcerpt: 'Born from a collaboration between alpine guides and AI researchers in the Swiss Alps.',
    storyFull: 'Two years ago, a team of alpine guides approached our R&D lab with a simple question: what if your GPS could think ahead? The Arc Navigator Pro is the answer. Trained on thousands of expedition routes, its onboard AI doesn\'t just show you where you are - it anticipates where you\'re going and the challenges you\'ll face. Field-tested across the Alps, Rockies, and Himalayan foothills.',
    inStock: true,
  },
  {
    sku: 'NAV-SOL-002',
    slug: 'solaris-compass-x',
    name: 'Solaris Compass X',
    tagline: 'Solar-powered digital compass with topo overlay',
    description: 'The Solaris Compass X never dies. Solar cells embedded in the sapphire crystal keep it charged indefinitely. Features topographic overlay on an always-on e-ink display with magnetic declination auto-adjust.',
    price: 289,
    category: 'navigation-gear',
    activities: ['hiking', 'camping', 'all-terrain'],
    techLevel: 'smart-hybrid',
    techSpecs: [
      { label: 'Display', value: '2.1"', unit: 'E-ink' },
      { label: 'Battery', value: 'Solar', unit: 'infinite' },
      { label: 'Accuracy', value: '0.5', unit: 'degrees' },
      { label: 'Weight', value: '68', unit: 'g' },
      { label: 'Water Rating', value: 'IPX7' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'teal',
    storyExcerpt: 'Inspired by ancient navigators who read the sun - now with a digital twist.',
    storyFull: 'The Solaris Compass X represents a philosophy: the best technology is the kind you never need to charge. We embedded micro solar cells directly into the sapphire crystal face, creating a compass that harvests ambient light even on overcast days. The e-ink topographic overlay gives you trail context without battery anxiety.',
    inStock: true,
  },
  {
    sku: 'NAV-TRL-003',
    slug: 'trailsync-beacon',
    name: 'TrailSync Beacon',
    tagline: 'Mesh-network trail marker for group expeditions',
    description: 'Drop TrailSync Beacons along your route and create a self-healing mesh network. Group members see each other\'s positions and the trail in real time - even without cell coverage.',
    price: 179,
    category: 'navigation-gear',
    activities: ['hiking', 'climbing', 'kayaking'],
    techLevel: 'full-digital',
    techSpecs: [
      { label: 'Range', value: '5', unit: 'km mesh' },
      { label: 'Battery', value: '168', unit: 'hrs' },
      { label: 'Nodes', value: 'Up to 24' },
      { label: 'Weight', value: '32', unit: 'g each' },
      { label: 'Pack', value: '4 beacons' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'glacier',
    storyExcerpt: 'Keeping groups connected when the trail splits.',
    storyFull: 'When a climbing team in Patagonia got separated by a sudden whiteout, they had no way to find each other. TrailSync Beacons were born from that experience. Each beacon talks to the others, forming a mesh network that extends coverage across kilometers of wild terrain.',
    inStock: true,
  },
  // ── Wearable Tech ────────────────────────────────────────────
  {
    sku: 'WRB-PLS-004',
    slug: 'pulse-ridge-watch',
    name: 'Pulse Ridge Watch',
    tagline: 'Expedition smartwatch with blood oxygen and storm alerts',
    description: 'The Pulse Ridge Watch monitors altitude sickness risk via SpO2 tracking, predicts incoming weather changes 6 hours ahead, and provides GPS breadcrumb navigation. Titanium case, sapphire crystal.',
    price: 699,
    compareAtPrice: 799,
    category: 'wearable-tech',
    activities: ['climbing', 'hiking', 'skiing'],
    techLevel: 'ai-powered',
    techSpecs: [
      { label: 'Display', value: '1.4"', unit: 'AMOLED' },
      { label: 'Battery', value: '14', unit: 'days' },
      { label: 'Sensors', value: 'SpO2, HR, Baro, Temp' },
      { label: 'Case', value: 'Grade 5 Titanium' },
      { label: 'Weight', value: '52', unit: 'g' },
      { label: 'Water', value: '10', unit: 'ATM' },
    ],
    featured: true,
    limitedDrop: false,
    accentColor: 'violet',
    storyExcerpt: 'Developed with high-altitude mountaineers who needed a watch that could save lives.',
    storyFull: 'At 7,000 meters, a headache can be the first sign of cerebral edema. The Pulse Ridge Watch was developed with expedition doctors to provide continuous SpO2 monitoring and AI-driven altitude sickness risk scoring. Its barometric storm prediction has been validated against professional weather stations across 200+ alpine locations.',
    inStock: true,
  },
  {
    sku: 'WRB-THR-005',
    slug: 'thermal-sync-band',
    name: 'ThermalSync Band',
    tagline: 'Adaptive heating wristband for extreme cold',
    description: 'The ThermalSync Band uses graphene heating elements controlled by skin temperature sensors. It auto-adjusts warmth to maintain optimal wrist temperature, extending dexterity in freezing conditions.',
    price: 189,
    category: 'wearable-tech',
    activities: ['skiing', 'climbing', 'camping'],
    techLevel: 'smart-hybrid',
    techSpecs: [
      { label: 'Heating', value: 'Graphene' },
      { label: 'Battery', value: '8', unit: 'hrs active' },
      { label: 'Temp Range', value: '-30 to 10', unit: 'C' },
      { label: 'Weight', value: '28', unit: 'g' },
      { label: 'Charge', value: 'USB-C', unit: '45min' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'coral',
    storyExcerpt: 'Keeping your hands nimble when the mercury drops.',
    storyFull: 'Frostbitten fingers end expeditions. The ThermalSync Band wraps your wrist in graphene micro-heaters that respond to your actual skin temperature, not just ambient conditions. Developed with ice climbers who need finger dexterity at -25C.',
    inStock: true,
  },
  {
    sku: 'WRB-VIS-006',
    slug: 'visor-hud-lite',
    name: 'Visor HUD Lite',
    tagline: 'Heads-up display sunglasses with trail data overlay',
    description: 'See your stats without looking down. Visor HUD Lite projects speed, elevation, heart rate, and navigation cues directly onto polarized lenses. Photochromic transition from clear to dark.',
    price: 429,
    category: 'wearable-tech',
    activities: ['trail-running', 'skiing', 'hiking'],
    techLevel: 'full-digital',
    techSpecs: [
      { label: 'Display', value: 'Micro-LED', unit: 'HUD' },
      { label: 'Battery', value: '12', unit: 'hrs' },
      { label: 'Lens', value: 'Photochromic', unit: 'Cat 0-3' },
      { label: 'Weight', value: '38', unit: 'g' },
      { label: 'Connect', value: 'BLE 5.3 + ANT+' },
    ],
    featured: true,
    limitedDrop: true,
    limitedDropEnds: limitedDropDate,
    accentColor: 'violet',
    storyExcerpt: 'The future of trail awareness, worn on your face.',
    storyFull: 'Visor HUD Lite grew from a frustration every trail runner knows: fumbling with a watch mid-stride. Our optics team miniaturized a micro-LED projector to just 2 grams, placing your vital data right where you\'re already looking - ahead. The photochromic lenses adapt from dawn starts to midday sun.',
    inStock: true,
  },
  {
    sku: 'WRB-EMR-007',
    slug: 'echo-mesh-earbuds',
    name: 'Echo Mesh Earbuds',
    tagline: 'Open-ear bone conduction with walkie-talkie mesh',
    description: 'Stay aware of your surroundings while communicating with your group up to 3km away. Echo Mesh Earbuds use bone conduction for audio and create an ad-hoc mesh radio network.',
    price: 249,
    category: 'wearable-tech',
    activities: ['hiking', 'climbing', 'kayaking', 'skiing'],
    techLevel: 'full-digital',
    techSpecs: [
      { label: 'Audio', value: 'Bone conduction' },
      { label: 'Range', value: '3', unit: 'km' },
      { label: 'Battery', value: '16', unit: 'hrs' },
      { label: 'Weight', value: '22', unit: 'g pair' },
      { label: 'Water', value: 'IP67' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'teal',
    storyExcerpt: 'Group communication that keeps you present in nature.',
    storyFull: 'Shouting across a valley is exhausting and unreliable. Echo Mesh Earbuds let your team communicate naturally, with bone conduction that keeps your ears open to the environment. The mesh radio works without any infrastructure - just clip them on and talk.',
    inStock: true,
  },
  // ── Expedition Equipment ─────────────────────────────────────
  {
    sku: 'EXP-PKR-008',
    slug: 'pack-reactor-60',
    name: 'Pack Reactor 60',
    tagline: 'Load-sensing backpack with kinetic energy harvesting',
    description: 'The Pack Reactor 60 converts your movement into electricity via a kinetic harvesting system integrated into the hip belt. Charges devices while you hike. Smart load distribution adjusts automatically.',
    price: 459,
    category: 'expedition-equipment',
    activities: ['hiking', 'camping', 'all-terrain'],
    techLevel: 'smart-hybrid',
    techSpecs: [
      { label: 'Volume', value: '60', unit: 'L' },
      { label: 'Harvest', value: '5W', unit: 'kinetic' },
      { label: 'Max Load', value: '25', unit: 'kg' },
      { label: 'Weight', value: '1.8', unit: 'kg' },
      { label: 'Ports', value: '2x USB-C' },
      { label: 'Material', value: 'Dyneema Composite' },
    ],
    featured: true,
    limitedDrop: false,
    accentColor: 'coral',
    storyExcerpt: 'Your movement is energy. This pack captures it.',
    storyFull: 'On multi-day treks, battery anxiety is real. The Pack Reactor 60 embeds a kinetic energy harvester into the hip belt suspension - every step generates a trickle of power that adds up over the day. By camp, you\'ve generated enough to charge your phone and GPS. The smart load system uses accelerometers to shift weight distribution as terrain changes.',
    inStock: true,
  },
  {
    sku: 'EXP-ROD-009',
    slug: 'carbon-trek-poles',
    name: 'Carbon Trek Poles',
    tagline: 'Ultra-light carbon poles with terrain-adaptive tips',
    description: 'Aerospace-grade carbon fiber poles that weigh next to nothing. Quick-lock adjustment and interchangeable tips for rock, snow, and mud. Ergonomic cork grips with moisture-wicking.',
    price: 219,
    category: 'expedition-equipment',
    activities: ['hiking', 'trail-running', 'climbing'],
    techLevel: 'analog',
    techSpecs: [
      { label: 'Material', value: 'Carbon Fiber', unit: 'aerospace' },
      { label: 'Weight', value: '185', unit: 'g each' },
      { label: 'Range', value: '100-135', unit: 'cm' },
      { label: 'Tips', value: '3 sets included' },
      { label: 'Grip', value: 'Cork + EVA' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'glacier',
    storyExcerpt: 'Lighter than you expect. Stronger than you need.',
    storyFull: 'We partnered with an aerospace composites lab to create poles with the highest strength-to-weight ratio available. Each pole uses uni-directional carbon fiber layup - the same technique used in racing yacht masts - for incredible stiffness at just 185 grams.',
    inStock: true,
  },
  {
    sku: 'EXP-FLT-010',
    slug: 'aqua-filter-pro',
    name: 'Aqua Filter Pro',
    tagline: 'UV-C + hollow fiber water purifier',
    description: 'Dual-stage purification combining UV-C sterilization with 0.1-micron hollow fiber filtration. Kills 99.999% of pathogens and filters particulates. Powered by a hand-crank dynamo.',
    price: 129,
    category: 'expedition-equipment',
    activities: ['camping', 'hiking', 'kayaking'],
    techLevel: 'smart-hybrid',
    techSpecs: [
      { label: 'Filtration', value: '0.1', unit: 'micron' },
      { label: 'UV-C', value: '99.999%', unit: 'kill rate' },
      { label: 'Flow', value: '1L per min' },
      { label: 'Power', value: 'Hand-crank dynamo' },
      { label: 'Weight', value: '220', unit: 'g' },
      { label: 'Lifespan', value: '10,000', unit: 'L' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'teal',
    storyExcerpt: 'Clean water anywhere, powered by your hands.',
    storyFull: 'After witnessing waterborne illness derail a humanitarian expedition, our founder committed to building the most effective portable purifier possible. The Aqua Filter Pro combines two complementary technologies: UV-C light destroys DNA of viruses and bacteria, while the hollow fiber membrane catches protozoa and particulates. The hand-crank dynamo means it never needs batteries.',
    inStock: true,
  },
  {
    sku: 'EXP-DRN-011',
    slug: 'scout-drone-mini',
    name: 'Scout Drone Mini',
    tagline: 'Pocket-sized trail reconnaissance drone',
    description: 'Launch the Scout Drone Mini to check trail conditions ahead, find water sources, or survey a campsite from above. Fits in your palm, flies for 25 minutes, and returns to hand automatically.',
    price: 799,
    category: 'expedition-equipment',
    activities: ['hiking', 'camping', 'all-terrain'],
    techLevel: 'ai-powered',
    techSpecs: [
      { label: 'Flight Time', value: '25', unit: 'min' },
      { label: 'Range', value: '4', unit: 'km' },
      { label: 'Camera', value: '4K', unit: '48MP' },
      { label: 'Weight', value: '249', unit: 'g' },
      { label: 'Folded', value: '9x6x5', unit: 'cm' },
      { label: 'Wind', value: 'Level 5', unit: 'resistance' },
    ],
    featured: false,
    limitedDrop: true,
    limitedDropEnds: limitedDropDate,
    accentColor: 'violet',
    storyExcerpt: 'Eyes in the sky, small enough for your pocket.',
    storyFull: 'The Scout Drone Mini was designed for one purpose: giving hikers and expedition leaders the ability to see what\'s ahead without committing to the trail. Its AI auto-return and obstacle avoidance mean you focus on the view, not the controls.',
    inStock: true,
  },
  // ── Shelter & Camp ───────────────────────────────────────────
  {
    sku: 'SHL-TNT-012',
    slug: 'aero-shelter-2p',
    name: 'Aero Shelter 2P',
    tagline: 'Inflatable ultralight 2-person tent',
    description: 'The Aero Shelter 2P replaces traditional poles with air beams. Inflate in 60 seconds with the integrated pump sack. Dyneema floor, silnylon fly, and 3-season protection at record-low weight.',
    price: 549,
    category: 'shelter-camp',
    activities: ['camping', 'hiking'],
    techLevel: 'analog',
    techSpecs: [
      { label: 'Weight', value: '980', unit: 'g' },
      { label: 'Capacity', value: '2 person' },
      { label: 'Setup', value: '60', unit: 'seconds' },
      { label: 'Floor', value: 'Dyneema' },
      { label: 'Packed', value: '30x12', unit: 'cm' },
      { label: 'Season', value: '3-season' },
    ],
    featured: true,
    limitedDrop: false,
    accentColor: 'coral',
    storyExcerpt: 'Sub-kilo shelter that sets up with a breath.',
    storyFull: 'Every gram matters on a through-hike. The Aero Shelter 2P ditches metal poles entirely in favor of air beams that achieve structural rigidity through internal baffles. The included pump sack doubles as a dry bag, and inflation takes about 15 breaths. At 980 grams for a full 2-person shelter, it redefines what ultralight means.',
    inStock: true,
  },
  {
    sku: 'SHL-SLP-013',
    slug: 'zero-g-sleep-system',
    name: 'Zero-G Sleep System',
    tagline: 'Self-heating sleeping pad with R-value 7.5',
    description: 'The Zero-G Sleep System uses phase-change material cells that absorb your body heat and release it back when temperatures drop. No batteries needed. Pair with any sleeping bag to boost comfort by 15F.',
    price: 329,
    category: 'shelter-camp',
    activities: ['camping', 'hiking'],
    techLevel: 'smart-hybrid',
    techSpecs: [
      { label: 'R-Value', value: '7.5' },
      { label: 'Heating', value: 'Phase-change', unit: 'passive' },
      { label: 'Weight', value: '650', unit: 'g' },
      { label: 'Thickness', value: '7.5', unit: 'cm' },
      { label: 'Packed', value: '25x13', unit: 'cm' },
      { label: 'Boost', value: '+15', unit: 'F' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'coral',
    storyExcerpt: 'Sleep warm without batteries.',
    storyFull: 'Phase-change materials have been used in space suits for decades. We adapted the technology for trail use, creating a sleeping pad that acts like a thermal battery. During the day, the PCM cells absorb heat. At night, they slowly release it, creating a warm microclimate that lasts all night.',
    inStock: true,
  },
  {
    sku: 'SHL-COK-014',
    slug: 'plasma-stove-x1',
    name: 'Plasma Stove X1',
    tagline: 'Electric arc lighter meets camp stove',
    description: 'The Plasma Stove X1 uses plasma arc technology to ignite any fuel source instantly, even in wind. Integrated with a titanium pot stand and windscreen. USB-C rechargeable, 200+ ignitions per charge.',
    price: 149,
    category: 'shelter-camp',
    activities: ['camping', 'hiking', 'all-terrain'],
    techLevel: 'full-digital',
    techSpecs: [
      { label: 'Ignition', value: 'Plasma arc' },
      { label: 'Ignitions', value: '200+', unit: 'per charge' },
      { label: 'Boil', value: '3.5', unit: 'min per L' },
      { label: 'Weight', value: '195', unit: 'g' },
      { label: 'Material', value: 'Titanium' },
      { label: 'Charge', value: 'USB-C' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'coral',
    storyExcerpt: 'Instant ignition in any condition.',
    storyFull: 'Fumbling with lighters in the rain is a universal camping frustration. The Plasma Stove X1 creates a high-temperature plasma arc that ignites fuel instantly, regardless of wind or moisture. The titanium construction keeps weight minimal while surviving years of abuse.',
    inStock: true,
  },
  // ── Illumination ─────────────────────────────────────────────
  {
    sku: 'ILM-HDL-015',
    slug: 'photon-beam-900',
    name: 'Photon Beam 900',
    tagline: 'Adaptive headlamp with reactive brightness',
    description: 'The Photon Beam 900 senses ambient light and adjusts output automatically. Look down at a map? It dims. Look up at the trail ahead? Full 900 lumens. Gesture control for mode switching.',
    price: 129,
    compareAtPrice: 159,
    category: 'illumination',
    activities: ['hiking', 'trail-running', 'camping', 'climbing'],
    techLevel: 'ai-powered',
    techSpecs: [
      { label: 'Output', value: '900', unit: 'lumens' },
      { label: 'Battery', value: '40', unit: 'hrs low' },
      { label: 'Beam', value: 'Adaptive', unit: 'reactive' },
      { label: 'Weight', value: '62', unit: 'g' },
      { label: 'Charge', value: 'USB-C' },
      { label: 'Water', value: 'IPX7' },
    ],
    featured: true,
    limitedDrop: false,
    accentColor: 'teal',
    storyExcerpt: 'A headlamp that reads the moment.',
    storyFull: 'The Photon Beam 900 has a light sensor and accelerometer that work together to understand what you\'re doing. Reading at camp? Gentle warm light. Running a dark trail? Maximum throw. The gesture control lets you switch modes with a wave - no fumbling with tiny buttons wearing gloves.',
    inStock: true,
  },
  {
    sku: 'ILM-LNT-016',
    slug: 'aurora-lantern',
    name: 'Aurora Lantern',
    tagline: 'Ambient camp lantern with northern lights mode',
    description: 'The Aurora Lantern provides warm campsite lighting and a mesmerizing aurora borealis color mode. Collapsible design, solar + USB-C charging, and a built-in power bank for emergency device charging.',
    price: 79,
    category: 'illumination',
    activities: ['camping'],
    techLevel: 'smart-hybrid',
    techSpecs: [
      { label: 'Output', value: '300', unit: 'lumens' },
      { label: 'Battery', value: '60', unit: 'hrs low' },
      { label: 'Charge', value: 'Solar + USB-C' },
      { label: 'Power Bank', value: '5,000', unit: 'mAh' },
      { label: 'Weight', value: '180', unit: 'g' },
      { label: 'Collapsed', value: '3', unit: 'cm tall' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'glacier',
    storyExcerpt: 'Bring the northern lights to any campsite.',
    storyFull: 'The Aurora Lantern was inspired by a camping trip under the real northern lights in Norway. We wanted to capture that ambient magic in a light you can carry anywhere. The aurora mode slowly cycles through greens, teals, and violets. In standard mode, it provides warm white light for 60 hours.',
    inStock: true,
  },
  {
    sku: 'ILM-MKR-017',
    slug: 'glow-trail-markers',
    name: 'Glow Trail Markers',
    tagline: 'Photoluminescent clip-on trail markers',
    description: 'Charge in sunlight for 10 minutes, glow for 12 hours. Clip Glow Trail Markers to branches and rocks to mark your route for nighttime return. Reusable, waterproof, and leave no trace.',
    price: 39,
    category: 'illumination',
    activities: ['hiking', 'camping', 'trail-running'],
    techLevel: 'analog',
    techSpecs: [
      { label: 'Glow Time', value: '12', unit: 'hrs' },
      { label: 'Charge', value: '10min', unit: 'sunlight' },
      { label: 'Pack', value: '8 markers' },
      { label: 'Weight', value: '8', unit: 'g each' },
      { label: 'Water', value: 'IPX8' },
      { label: 'Material', value: 'Strontium Aluminate' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'teal',
    storyExcerpt: 'Ancient glow-in-the-dark, perfected.',
    storyFull: 'Strontium aluminate is the most efficient photoluminescent material known. We shaped it into rugged, clip-on markers that charge from any light source and glow bright enough to spot from 50 meters. No batteries, no waste, no trace left behind.',
    inStock: true,
  },
  {
    sku: 'ILM-BIV-018',
    slug: 'bivouac-string-lights',
    name: 'Bivouac String Lights',
    tagline: 'Solar string lights for basecamp ambiance',
    description: 'Ten meters of warm LED string lights with a solar panel and USB-C backup. Weather-sealed for permanent basecamp installation or pack them for single-night bivouacs. Warm white and color modes.',
    price: 59,
    category: 'illumination',
    activities: ['camping'],
    techLevel: 'analog',
    techSpecs: [
      { label: 'Length', value: '10', unit: 'm' },
      { label: 'LEDs', value: '50 warm white' },
      { label: 'Battery', value: '20', unit: 'hrs' },
      { label: 'Charge', value: 'Solar + USB-C' },
      { label: 'Weight', value: '120', unit: 'g' },
      { label: 'Water', value: 'IP65' },
    ],
    featured: false,
    limitedDrop: false,
    accentColor: 'glacier',
    storyExcerpt: 'Turn any campsite into home.',
    storyFull: 'There\'s something about string lights that transforms a campsite from a stop into a destination. The Bivouac String Lights pack down to the size of a tennis ball and give you 10 meters of warm ambiance. The solar panel charges during the day, and USB-C is there for cloudy stretches.',
    inStock: true,
  },
]
